In [47]:
import pandas as pd
import numpy as np
df=pd.read_csv(r"Downloads/archive (1).zip")

In [4]:
df

       Index  Height(Inches)  Weight(Pounds)
0          1        65.78331        112.9925
1          2        71.51521        136.4873
2          3        69.39874        153.0269
3          4        68.21660        142.3354
4          5        67.78781        144.2971
...      ...             ...             ...
24995  24996        69.50215        118.0312
24996  24997        64.54826        120.1932
24997  24998        64.69855        118.2655
24998  24999        67.52918        132.2682
24999  25000        68.87761        124.8742

[25000 rows x 3 columns]

In [5]:
df.shape

(25000, 3)

In [6]:
df.size

75000

In [7]:
df.info

<bound method DataFrame.info of        Index  Height(Inches)  Weight(Pounds)
0          1        65.78331        112.9925
1          2        71.51521        136.4873
2          3        69.39874        153.0269
3          4        68.21660        142.3354
4          5        67.78781        144.2971
...      ...             ...             ...
24995  24996        69.50215        118.0312
24996  24997        64.54826        120.1932
24997  24998        64.69855        118.2655
24998  24999        67.52918        132.2682
24999  25000        68.87761        124.8742

[25000 rows x 3 columns]>

In [8]:
df.describe()

              Index  Height(Inches)  Weight(Pounds)
count  25000.000000    25000.000000    25000.000000
mean   12500.500000       67.993114      127.079421
std     7217.022701        1.901679       11.660898
min        1.000000       60.278360       78.014760
25%     6250.750000       66.704397      119.308675
50%    12500.500000       67.995700      127.157750
75%    18750.250000       69.272958      134.892850
max    25000.000000       75.152800      170.924000

In [9]:
df.isnull()

       Index  Height(Inches)  Weight(Pounds)
0      False           False           False
1      False           False           False
2      False           False           False
3      False           False           False
4      False           False           False
...      ...             ...             ...
24995  False           False           False
24996  False           False           False
24997  False           False           False
24998  False           False           False
24999  False           False           False

[25000 rows x 3 columns]

In [10]:
df.isnull().sum()

Index             0
Height(Inches)    0
Weight(Pounds)    0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df.dtypes

Index               int64
Height(Inches)    float64
Weight(Pounds)    float64
dtype: object

In [13]:
df['BMI']=(df['Weight(Pounds)']/(df['Height(Inches)']**2))*703

In [14]:
df

       Index  Height(Inches)  Weight(Pounds)        BMI
0          1        65.78331        112.9925  18.355808
1          2        71.51521        136.4873  18.760773
2          3        69.39874        153.0269  22.336747
3          4        68.21660        142.3354  21.502458
4          5        67.78781        144.2971  22.075458
...      ...             ...             ...        ...
24995  24996        69.50215        118.0312  17.177330
24996  24997        64.54826        120.1932  20.279916
24997  24998        64.69855        118.2655  19.862061
24998  24999        67.52918        132.2682  20.390497
24999  25000        68.87761        124.8742  18.504268

[25000 rows x 4 columns]

In [15]:
def assign_label(BMI):
    if BMI < 18.5:
        return 'Underweight'
    elif 18.5<=BMI<25:
        return 'Normal'
    elif 25 <=BMI<30:
        return 'Overweight'
    else:
        return 'Obese'

In [16]:
df['Category']=df['BMI'].apply(assign_label)

In [17]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, accuracy_score

In [18]:
X=df[['Height(Inches)','Weight(Pounds)']]
y=df['Category']

In [19]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [20]:
model=DecisionTreeClassifier(max_depth=5,random_state=42)

In [21]:
model.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=5, random_state=42)

In [22]:
y_pred=model.predict(X_test)

In [23]:
acc=accuracy_score(y_pred ,y_test)

In [24]:
acc

0.969

In [25]:
from sklearn.metrics import classification_report
print("---Full Classification Report---")
print(classification_report(y_test,y_pred))

---Full Classification Report---
              precision    recall  f1-score   support

      Normal       0.97      0.98      0.98      3513
  Overweight       0.00      0.00      0.00         1
 Underweight       0.96      0.94      0.95      1486

    accuracy                           0.97      5000
   macro avg       0.64      0.64      0.64      5000
weighted avg       0.97      0.97      0.97      5000

D:\New folder\envs\dev\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
D:\New folder\envs\dev\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
D:\New folder\envs\dev\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [26]:
print("---Class Distribution across the entire dataset---")
print(df['Category'].value_counts())

---Class Distribution across the entire dataset---
Category
Normal         17541
Underweight     7453
Overweight         6
Name: count, dtype: int64

##baseline model issue(imbalanced class issue) discovered a class imbalance where overweight had only 6 samples hence removing the 6 outlier rows to create a clean,robust model predicting Normal vs Underweight.

In [27]:
df_clean=df[df['Category']!='Overweight']

In [28]:
X_clean=df_clean[['Height(Inches)','Weight(Pounds)']]
y_clean=df_clean['Category']

In [29]:
X_train_c,X_test_c,y_train_c,y_test_c=train_test_split(X_clean,y_clean,test_size=0.2,random_state=42)

In [30]:
binary_model=DecisionTreeClassifier(max_depth=5,random_state=42)
binary_model.fit(X_train_c,y_train_c)

DecisionTreeClassifier(max_depth=5, random_state=42)

In [31]:
y_pred_c=binary_model.predict(X_test_c)

In [32]:
print("---Full Classification Report---")
print(classification_report(y_test_c,y_pred_c))

---Full Classification Report---
              precision    recall  f1-score   support

      Normal       0.97      0.98      0.98      3552
 Underweight       0.96      0.93      0.94      1447

    accuracy                           0.97      4999
   macro avg       0.97      0.96      0.96      4999
weighted avg       0.97      0.97      0.97      4999

In [33]:
##lets add a linear regression model to predict a persons exact numeric weight based directly on their height.

In [34]:
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

In [35]:
X_reg=df_clean[['Height(Inches)']]
y_reg=df_clean['Weight(Pounds)']

In [36]:
X_train_r,X_test_r,y_train_r,y_test_r=train_test_split(X_reg,y_reg,test_size=0.2,random_state=42)

In [37]:
reg_model=LinearRegression()
reg_model.fit(X_train_r,y_train_r)

LinearRegression()

In [42]:
slope=reg_model.coef_[0]
intercept=reg_model.intercept_
r2_score=reg_model.score(X_test_r,y_test_r)
print(f"Regression model R^2 score:{r2_score:.4f}")
print(f" Clean Formula:Weight={slope:.2f}*Height - {abs(intercept):.2f}")

Regression model R^2 score:0.2533
 Clean Formula:Weight=3.10*Height - 83.61

In [43]:
##LIVE DEMO:Testing the Trained Models on Custom Data 
#The cell below demonstrates how to use our trained models to make instant predictions on new,unseen data inputs.

In [44]:
#Demo 1: using the Binary Classifier to pedict a discrete target category

In [54]:
#input format:[[Height_in_Inches,Weight_in_Pounds]]
demo_data=pd.DataFrame([[65,120]],columns=['Height(Inches)','Weight(Pounds)'])
class_pred=binary_model.predict(demo_data)

In [55]:
print("---Live Classifier Prediction Demo---")
print(f"Input:Height=65 in,Weight=120 lbs")
print(f"Model Prediction Category ->{class_pred[0]}")

---Live Classifier Prediction Demo---
Input:Height=65 in,Weight=120 lbs
Model Prediction Category ->Normal

In [59]:
demo_data_2=pd.DataFrame([[59,88.18]],columns=['Height(Inches)','Weight(Pounds)'])
class_pred_2=binary_model.predict(demo_data_2)

In [60]:
print("---Live Classifier Prediction Demo---")
print(f"Input:Height=59 in,Weight=88.18 lbs")
print(f"Model Prediction Category ->{class_pred_2[0]}")

---Live Classifier Prediction Demo---
Input:Height=59 in,Weight=88.18 lbs
Model Prediction Category ->Underweight

In [61]:
##using the linear regression model to predict a continous numerical value

In [62]:
##input format=[[Height(Inches)]]
demo_height=pd.DataFrame([[59]],columns=['Height(Inches)'])
weight_pred=reg_model.predict(demo_height)

In [64]:
print("---Live Regression Prediction Demo---")
print(f"Input:Height=59 in")
print(f"Model Prediction Weight ->{weight_pred[0]:.2f} lbs")

---Live Regression Prediction Demo---
Input:Height=59 in
Model Prediction Weight ->99.18 lbs